name: email-processing
services:
# ------------
# azure service emulators
# ------------
  # azurite emulator
  azurite:
    container_name: "azurite"
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - dealership-assistant

  # service bus emulator
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:${EMULATOR_HTTP_PORT:-5300}"
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: ${ACCEPT_EULA}
      EMULATOR_HTTP_PORT: ${EMULATOR_HTTP_PORT:-5300}
      SQL_WAIT_INTERVAL: 15
    depends_on:
      - mssql
    networks:
      - dealership-assistant

  # mssql server for service bus emulator
  mssql:
    container_name: "mssql"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    networks:
      - dealership-assistant

  # cosmos db emulator
  cosmosdb:
    container_name: "cosmosdb-emulator"
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    restart: always
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 5
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: ${AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE:-"0.0.0.0"}
    ports:
      - "8081:8081"
      - "10255:10255"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    networks:
      - dealership-assistant

# ------------
# application services
# ------------
  # email processing service
  email-processing-service:
    container_name: "email-processing-service"
    image: carclinchda/email-processing-service:latest
    pull_policy: always
    environment:
      FUNCTIONS_WORKER_RUNTIME_VERSION: "3.12"
      AZURE_FUNCTIONS_ENVIRONMENT: "Development"
      WEBSITE_HOSTNAME: "localhost:80"
      AzureWebJobsStorage: "UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite"
      AzureWebJobsServiceBus: ${SB_CONNECTION_STRING}
      ACS_CONNECTION_STRING: ${ACS_CONNECTION_STRING}
      SENDER_ADDRESS: "${SENDER_ADDRESS}"
      COSMOS_CONNECTION_STRING: ${COSMOS_DB_CONNECTION_STRING}
    depends_on:
      - emulator
      - azurite
      - cosmosdb
    networks:
      - dealership-assistant

  # form backend function
  backend:
    container_name: "form-backend-service"
    image: carclinchda/form-backend-service:vehicleId
    pull_policy: always
    ports:
      - "7071:80"
    environment:
      FUNCTIONS_WORKER_RUNTIME_VERSION: "3.12"
      AZURE_FUNCTIONS_ENVIRONMENT: "Development"
      WEBSITE_HOSTNAME: "localhost:80"
      AzureWebJobsStorage: ${STORAGE_CONNECTION_STRING}
      COSMOS_ENDPOINT: "${COSMOS_ENDPOINT}"
      COSMOS_KEY: "${COSMOS_KEY}"
      COSMOS_DATABASE: "${COSMOS_DATABASE:-dealership}"
      SERVICE_BUS_CONNECTION_STRING: ${SB_CONNECTION_STRING}
    depends_on:
      - emulator
      - azurite
      - cosmosdb
    networks:
      - dealership-assistant

  # form frontend service
  frontend:
    container_name: "form-frontend-service"
    image: carclinchda/form-frontend-service:vehicleId
    pull_policy: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - dealership-assistant

networks:
  dealership-assistant: